services:
  - type: web
    name: bookish-backend
    env: node
    rootDir: backend
    branch: ujjwal-1
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_PREMIUM_PRICE_ID
        sync: false
      - key: STRIPE_PREMIUM_PLUS_PRICE_ID
        sync: false
